# Generated by Django 3.0.5 on 2020-04-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Walfare',
            fields=[
                ('prize_number', models.AutoField(primary_key=True, serialize=False)),
                ('prize_name', models.CharField(max_length=40)),
                ('prize_points', models.IntegerField(default=0)),
                ('prize_introduction', models.TextField()),
                ('prize_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
