# Generated by Django 3.0.5 on 2020-04-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('exchange_number', models.AutoField(primary_key=True, serialize=False)),
                ('volunteer_number', models.IntegerField(default=0)),
                ('prize_number', models.IntegerField(default=True)),
                ('exchange_time', models.DateField()),
                ('exchanged', models.BooleanField(default=True)),
            ],
        ),
    ]
