# Generated by Django 3.0.5 on 2020-04-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('volunteer_number', models.AutoField(primary_key=True, serialize=False)),
                ('volunteer_name', models.CharField(max_length=20)),
                ('sex', models.BooleanField(default=True)),
                ('age', models.IntegerField(null=True)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('cultural_level', models.CharField(max_length=20)),
                ('activity_points', models.IntegerField(default=0)),
                ('available_points', models.IntegerField(default=0)),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Users')),
            ],
        ),
    ]
