# Generated by Django 3.0.5 on 2020-05-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Activity', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users')),
                ('activity_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity.Activity')),
            ],
        ),
    ]
