# Generated by Django 3.0.5 on 2020-05-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.BooleanField(),
        ),
    ]
