# Generated by Django 3.0.5 on 2020-04-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('helper_number', models.AutoField(primary_key=True, serialize=False)),
                ('helper_name', models.CharField(max_length=20)),
                ('helper_tel', models.CharField(max_length=20)),
                ('helper_address', models.CharField(max_length=40)),
                ('account', models.CharField(max_length=20)),
            ],
        ),
    ]
